import * as d from '@3sln/dodo';

export default driver => {
  driver.panel('Demo', (container, signal) => {
    const vnode = d.div(
      {$styling: {border: '1px solid #ccc', padding: '1em'}},
      d.h2('Generated by Dodo'),
      d.p('This structure was created using the HTML helper functions.'),
      d.p('The equivalent using h() would be:'),
      d.pre(
        d.code(
          `d.h('div', { $styling: { border: '1px solid #ccc', padding: '1em' } },
  d.h('h2', 'Generated by Dodo'),
  d.h('p', 'This structure was created using the HTML helper functions.'),
);`,
        ),
      ),
    );

    d.reconcile(container, [vnode]);

    signal.addEventListener('abort', () => {
      d.reconcile(container, []);
    });
  });
};
