import * as d from '@3sln/dodo';

export default driver => {
  driver.panel('Demo', (container, signal) => {
    const vnode = d
      .div(
        d.h2('Generated by Dodo'),
        d.p('This structure was created using the HTML helper functions.'),
        d.p('The equivalent using h() would be:'),
        d.pre(
          d.code(
            `d.h('div', null,
  d.h('h2', 'Generated by Dodo'),
  d.h('p', 'This structure was created using the HTML helper functions.'),
).style({ border: '1px solid #ccc', padding: '1em' });`,
          ),
        ),
      )
      .style({border: '1px solid #ccc', padding: '1em'});

    d.reconcile(container, [vnode]);

    signal.addEventListener('abort', () => {
      d.reconcile(container, []);
    });
  });
};
